programming_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from cms import views
# from chusebutton.views import chusebutton


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', chusebutton),
    path('', include('shop.urls')),
    path('firstpage/', views.first_page, name='firstpage'),
    path('captcha/', include('captcha.urls')),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
    path('thanks/', views.thanks_page, name='thanks_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('', ShopHome.as_view(), name='index'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', ShopCategory.as_view(), name='category'),
    path('sellthing/', SellThing.as_view(), name='sell_thing'),
    path('useditems/', UsedItems.as_view(), name='useditems'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='shop/logout.html'), name='logout'),
    path('contact/', ContactFormView.as_view(), name="contact")
]

cms/models.py
from django.db import models


class CmsSlider(models.Model):
    cms_img = models.ImageField(upload_to="slider_img")
    cms_title = models.CharField(max_length=300, verbose_name="Заголовок")
    cms_text = models.CharField(max_length=300, verbose_name="Текст")
    cms_css = models.CharField(max_length=300, null=True, default="-", verbose_name="Класс CSS")

    def __str__(self):
        return self.cms_title

    class Meta:
        verbose_name = "Слайд"
        verbose_name_plural = "Слайды"

price/models.py
from django.db import models



class PriceCard(models.Model):
    pc_value = models.CharField(max_length=20, verbose_name="Цена")
    pc_description = models.CharField(max_length=200, verbose_name="Описание")

    def __str__(self):
        return self.pc_value

    class Meta:
        verbose_name = "Цена"
        verbose_name_plural = "Цены"


class PriceTable(models.Model):
    pt_title = models.CharField(max_length=200, verbose_name="Услуга")
    pt_old_price = models.CharField(max_length=200, verbose_name="Старая цена")
    pt_new_price = models.CharField(max_length=200, verbose_name="Новая цена")


    def __str__(self):
        return self.pt_title

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

crm/forms.py
from django import forms


class OrderForm(forms.Form):
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # whats_happen = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    service_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # foto = forms.ImageField(upload_to='repairDevice/')
    # not_work = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))

cms/views.py
from django.shortcuts import render

from .models import CmsSlider
from price.models import PriceTable, PriceCard
from crm.models import Order
from crm.forms import OrderForm
from telebot.sendmessage import send_telegram


def first_page(request):
    slider_list = CmsSlider.objects.all()
    pc_1 = PriceCard.objects.get(pk=1)
    pc_2 = PriceCard.objects.get(pk=2)
    pc_3 = PriceCard.objects.get(pk=3)
    form = OrderForm()
    price_table = PriceTable.objects.all()
    dict_obj = {
        'slider_list': slider_list,
        'pc_1': pc_1,
        'pc_2': pc_2,
        'pc_3': pc_3,
        'price_table': price_table,
        'form': form,
    }
    return render(request, 'cms/index.html', dict_obj)


def thanks_page(request):
    if request.POST:
        name = request.POST['name']
        phone = request.POST['phone']
        service_name = request.POST['service_name']
        element = Order(order_name=name, order_phone=phone, order_service_name=service_name)
        element.save()
        send_telegram(tg_name=name, tg_phone=phone, tg_service_name=service_name)
        return render(request, 'cms/thanks.html', {'name': name})
    else:
        return render(request, 'cms/thanks.html')

price/views.py
from django.shortcuts import render

# Create your views here.

cms/templates/cms/base_carusel.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/style_carusel.css' %}" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Простой сайт</title>
  </head>
  <body>
  <div class="bg-light">
	<nav class="navbar navbar-light bg-light container">
	  <a class="logo-top" href="{% url 'firstpage' %}">
	    <img src="{% static 'cms/logo.png' %}" class="d-inline-block align-top" alt="" loading="lazy">

	  </a>
	  <div class="contact-top">
                <a class="whatsapp-number" href="https://web.whatsapp.com/"></a>
                <a class="telegram-number" href="https://t.me/"></a>
              <a class="phone-number text-dark" href="tel:+79099999999">
              	<h5>+7(909)-999-99-99</h5></a>
      </div>
	</nav>
  </div>

  {% block content %}
  {% endblock %}

  <footer class="bg-light">
  		<div class="container">
  			<nav class="navbar navbar-light container">
			    <a class="logo-bottom" href="{% url 'firstpage' %}}">
			    	<img src="./img/logo.png" class="d-inline-block align-top" alt="" loading="lazy">
			    </a>
	  			<div class="contact-top">
	                <a class="whatsapp-number" href="https://web.whatsapp.com/"></a>
	                <a class="telegram-number" href="https://t.me/"></a>
	              	<a class="phone-number text-dark" href="tel:+79099999999">
	              	<h5>+7(909)-999-99-99</h5></a>
      			</div>
			</nav>
  		</div>
  	    </footer>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

cms/templates/cms/carusel.html
<!-- карусель -->
  	<section>
  		<div id="carouselExampleCaptions" class="carousel slide container" data-ride="carousel">
			<div class="carousel-inner">
			{% for slide in slider_list %}
		    <div class="carousel-item {{ slide.cms_css}}">
		      <img src="{{ slide.cms_img.url }}" class="d-block w-100"  alt="...">
		      <div class="carousel-caption d-none d-md-block">
		        <h5 class="slaider_h">{{ slide.cms_title }}</h5>
		        <p class="slaider_p">{{ slide.cms_text }}</p>
		      </div>
		    </div>
			{% endfor %}
		  </div>
		  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
  	</section>

cms/templates/cms/index.html
{% extends 'cms/base_carusel.html' %}
{% block content %}
<h1>Страница СЛАЙДОВ</h1>
<p>Страница: index.html</p>
    <!-- Карусель -->
    {% include 'cms/carusel.html' %}
    <!-- Карточки -->
    {% include 'cms/price.html' %}
    <!-- форма -->
  	<section>
  		<div class="container class_form">
  			<h1 class="text-3">Оставь заявку и получить услугу</h1>
  			<div class="row justify-content-center">

				<form action="{% url 'thanks_page' %}" method="POST" style="width: 50%;">
				{% csrf_token %}
			  <div class="form-group row">
			    <label for="id_name" class="col-sm-2 col-form-label">Имя</label><br>

				  {{ form.name }}

			    <div class="">
			    </div>
			  </div>
			  <div class="form-group row">
			    <label for="id_phone" class="col-sm-2 col-form-label">Телефон</label><br>

				  {{ form.phone }}

			    <div class="">
			    </div>
			  </div>
                <div class="form-group row">
			    <label for="service_name" class="col-sm-2 col-form-label">Назвагие услуги</label><br>

				  {{ form.service_name }}

			    <div class="">
			    </div>
			  </div>

                <div style="float: right;" class="form-group row">
			      <button type="submit" class="btn btn-success">ОСТАВИТЬ ЗАЯВКУ</button>
			  </div>
				</form>


			</div>
  		</div>
  	</section>

{% endblock %}

cms/templates/cms/price.html
<!-- Карточки -->
  	<section>
  		<div class="container">
  			<h1 class="text-3">ПАКЕТЫ УСЛУГ</h1>
  			<div class="row justify-content-center">
  				<div class="card product_card" style="width: 18rem; background-color: #33CCFF;">
				  <div class="card-body">
				    <h5 class="card-title">МИНИМУМ</h5>
				    <p class="card-text">Windows, office, драйвера, базовая настройка</p>
				    <h3>{{ pc_1 }} руб.</h3>
				  </div>
				</div>
				<div class="card product_card" style="width: 18rem; background-color: #FF9900;">
				  <div class="card-body">
				    <h5 class="card-title">СТАНДАРТ</h5>
				    <p class="card-text">Windows, office, антивирус, драйвера и др.</p>
				    <h3>{{ pc_2 }} руб.</h3>
				  </div>
				</div>
				<div class="card product_card" style="width: 18rem; background-color: #66FF66;">
				  <div class="card-body">
				    <h5 class="card-title">ДЛЯ ДОМА</h5>
				    <p class="card-text">Windows, до 20 программ, антивирус, все драйвера и др.</p>
				    <h3>{{ pc_3 }} руб.</h3>
				  </div>
				</div>
  			</div>
  		</div>
  	</section>
  	<!-- Таблица -->
  	<section>
  		<div class="container">
  			<h1 class="text-3">Цены на услуги</h1>
  			<table class="table table_one">
			  <thead class="alert-success">
			    <tr>
			      <th scope="col">Услуга</th>
			      <th scope="col">Старая цена</th>
			      <th scope="col">Новая цена</th>
			    </tr>
			  </thead>
			  <tbody>
				{% for obj in price_table %}
			    <tr>
			      <td>{{ obj.pt_title }}</td>
			      <td><del>{{ obj.pt_old_price }}</del></td>
			      <td>{{ obj.pt_new_price }}</td>
			    </tr>
				{% endfor %}
			  </tbody>
			</table>
  		</div>
  	</section>

cms/templates/cms/thanks.html
{% extends 'cms/base_carusel.html' %}

{% block thanks %}

	<!-- Спасибо -->
  	<section>
  		<div class="container">
  			<div class="thank"><h1>Спасибо за заявку!</h1></div>
  		</div>
  	</section>
  	<!-- Спасибо -->

{% endblock %}